Repository dpc-sdp/ripple-framework, pull requests merged in 2022-10, with the labels that each got.

#249 [R20-312] Page action feedback
  packages/ripple-ui-core/src/components/page-action/page-action.stories.mdx
  packages/ripple-ui-core/src/styles/components/_document.css
Labels: Needs Code review, uncontroversial

#254 [R20-90]: more fixed sizing for large screens
  packages/ripple-ui-core/src/components/header/header-actions.css
  packages/ripple-ui-core/src/components/header/header-actions.vue
  packages/ripple-ui-core/src/components/header/header-graphic.vue
  packages/ripple-ui-core/src/components/header/header-links.css
  packages/ripple-ui-core/src/components/header/header-links.vue
  packages/ripple-ui-core/src/components/header/header.css
  packages/ripple-ui-core/src/components/header/hero-header.stories.mdx
  packages/ripple-ui-core/src/components/header/hero-header.vue
  packages/ripple-ui-core/src/components/image/constants.ts
Labels: Needs Code review

#252 [R20-314] footer feedback items
  packages/ripple-ui-core/src/components/acknowledgement/acknowledgement.css
  packages/ripple-ui-core/src/components/footer/footer.css
  packages/ripple-ui-core/src/components/footer/footer.stories.mdx
  packages/ripple-ui-core/src/components/footer/footer.vue
  packages/ripple-ui-core/src/components/footer/nav-section.css
  packages/ripple-ui-core/src/components/footer/nav-section.vue
  packages/ripple-ui-core/src/components/text-link/text-link.css
  packages/ripple-ui-core/src/composables/useExpandable.ts
Labels: Needs Code review

#257 fix(@dpc-sdp/ripple-ui-core): patch @outlinestudio/designtokenscss
  patches/@outlinestudio+designtokenscss+1.0.6.patch
Labels: bug, Needs Code review

#259 [R20-278] update vertical nav buttons
  packages/ripple-ui-core/src/components/vertical-nav/vertical-nav.css
Labels: Needs Code review, uncontroversial

#260 [R20-310] update focus state and firefox fix
  packages/ripple-ui-core/src/styles/utilities/_focus.css
Labels: Needs Code review

#258 [R20-88] added campaign banner component
  packages/ripple-ui-core/src/components/campaign-banner/campaign-banner.css
  packages/ripple-ui-core/src/components/campaign-banner/campaign-banner.vue
  packages/ripple-ui-core/src/components/campaign-banner/primary-campaign.stories.mdx
  packages/ripple-ui-core/src/components/campaign-banner/primary-campaign.vue
  packages/ripple-ui-core/src/components/campaign-banner/secondary-campaign.stories.mdx
  packages/ripple-ui-core/src/components/campaign-banner/secondary-campaign.vue
  packages/ripple-ui-core/src/components/layout/layout.stories.mdx
Labels: Needs Code review

#263 [R20-88] update spelling
  packages/ripple-ui-core/src/components/campaign-banner/campaign-banner.css
Labels: uncontroversial

#265 fix(@dpc-sdp/ripple-ui-core): :bug: fix horizontal scroll appearing on windows
  packages/ripple-ui-core/src/components/campaign-banner/campaign-banner.css
Labels: Needs Code review

#264 [R20-299] - Update typography sizes
  packages/ripple-ui-core/src/styles/_vars.css
  packages/ripple-ui-core/src/styles/utilities/_typography.css
  packages/ripple-ui-core/tokens/settings/type.yaml
Labels: Needs Code review

#267 [R20-309] design feedback
  packages/ripple-ui-core/src/components/alert/alert.css
  packages/ripple-ui-core/src/components/alert/alert.stories.mdx
  packages/ripple-ui-core/src/components/alert/alert.vue
Labels: Needs Code review

#268 fix(@dpc-sdp/ripple-ui-core): :bug: change accordion mapping ids to strings
  packages/ripple-tide-grant/component.mapping.ts
  packages/ripple-tide-landing-page/src/component.mapping.ts
Labels: Needs Code review

#270 Feature/primary nav integration
  examples/nuxt-app/test/features/site/theme.ts
  packages/ripple-ui-core/src/assets/icons/custom/icon-search.svg
  packages/ripple-ui-core/src/components/header/header.css
  packages/ripple-ui-core/src/components/layout/layout.vue
  packages/ripple-ui-core/src/components/primary-nav/primary-nav.css
  packages/ripple-ui-core/src/components/primary-nav/primary-nav.vue
Labels: Needs Code review
