Repository dpc-sdp/ripple-framework, pull requests merged in 2022-12, with the labels that each got.

#331 [R20-142] add margin to topic tags
  packages/ripple-tide-api/src/nuxt/components/BaseLayout.vue
Labels: uncontroversial

#332 feat(@dpc-sdp/ripple-ui-core): adding missed breakpoints import
  packages/ripple-ui-core/src/components/header/header-graphic.css
  packages/ripple-ui-core/src/components/header/header-links.css
Labels: uncontroversial

#333 [R20-347] - Primary nav search form feedback
  packages/ripple-ui-core/src/components/primary-nav/mega-menu-action.vue
  packages/ripple-ui-core/src/components/primary-nav/mega-menu-back-button.vue
  packages/ripple-ui-core/src/components/primary-nav/mega-menu-list.vue
  packages/ripple-ui-core/src/components/primary-nav/mega-menu.vue
  packages/ripple-ui-core/src/components/primary-nav/nav-bar-action.vue
  packages/ripple-ui-core/src/components/primary-nav/nav-bar.vue
  packages/ripple-ui-core/src/components/primary-nav/primary-nav.css
  packages/ripple-ui-core/src/components/primary-nav/primary-nav.stories.mdx
  packages/ripple-ui-core/src/components/primary-nav/primary-nav.vue
  packages/ripple-ui-core/src/components/primary-nav/quick-exit.vue
  packages/ripple-ui-core/src/components/primary-nav/search-form.vue
Labels: Needs Code review

#334 feat(@dpc-sdp/ripple-ui-core): Graphic fix, empty slot checks
  packages/ripple-tide-api/src/nuxt/components/BaseLayout.vue
  packages/ripple-tide-api/src/nuxt/components/ErrorPage.vue
  packages/ripple-ui-core/src/components/error-message/error-message.css
  packages/ripple-ui-core/src/components/layout/layout.css
  packages/ripple-ui-core/src/components/layout/layout.vue
Labels: Needs Code review

#340 [R20-278] - Vertical nav feedback
  packages/ripple-ui-core/src/components/vertical-nav/vertical-nav.vue
Labels: Needs Code review, uncontroversial

#344 fix(@dpc-sdp/ripple-ui-forms): tidied up form alert styling
  packages/ripple-ui-forms/src/components/RplFormAlert/RplFormAlert.vue
Labels: uncontroversial

#348 Fix flag height
  packages/ripple-ui-core/src/components/acknowledgement/acknowledgement.css
Labels: uncontroversial

#346 feat(@dpc-sdp/ripple-ui-core): remaining copy update
  packages/ripple-ui-forms/src/components/RplFormCounter/RplFormCounter.vue
  packages/ripple-ui-forms/src/components/RplFormInput/RplFormInput.vue
  packages/ripple-ui-forms/src/components/RplFormTextarea/RplFormTextarea.vue
Labels: Needs Code review

#343 [RPL20-348] - Mega menu feedback
  .eslintrc.js
  .storybook/public/themes/dark-on-light.css
  .storybook/themes.json
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/mega-menu-action.vue
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/mega-menu-back-button.vue
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/mega-menu-list.vue
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/mega-menu.css
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/mega-menu.vue
  packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/nav-bar-action.vue
  packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/nav-bar.css
  packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/nav-bar.vue
  packages/ripple-ui-core/src/components/primary-nav/components/quick-exit/quick-exit.vue
  packages/ripple-ui-core/src/components/primary-nav/components/search-form/search-form.css
  packages/ripple-ui-core/src/components/primary-nav/components/search-form/search-form.vue
  packages/ripple-ui-core/src/components/primary-nav/constants.ts
  packages/ripple-ui-core/src/components/primary-nav/mega-menu-action.vue
  packages/ripple-ui-core/src/components/primary-nav/mega-menu.vue
  packages/ripple-ui-core/src/components/primary-nav/primary-nav.css
  packages/ripple-ui-core/src/components/primary-nav/primary-nav.vue
Labels: Needs Code review

#353 chore(@dpc-sdp/ripple-ui-core): move stories out of WIP
  packages/ripple-ui-core/src/components/card-carousel/card-carousel.stories.mdx
  packages/ripple-ui-core/src/components/error-message/error-message.stories.mdx
  packages/ripple-ui-core/src/components/media-embed/media-embed.stories.mdx
  packages/ripple-ui-core/src/components/media-gallery/media-gallery.stories.mdx
Labels: uncontroversial

#351 fix(@dpc-sdp/ripple-ui-forms): added missing breakpoint import
  packages/ripple-ui-forms/src/components/RplFormAlert/RplFormAlert.css
Labels: uncontroversial

#356 [R20-301] update exports and media template
  examples/nuxt-app/test/features/media/media.ts
  packages/ripple-tide-media/src/components/tide-media-body.vue
  packages/ripple-tide-media/src/pages/audio/tide-media-audio.vue
  packages/ripple-tide-media/src/pages/embedded-video/tide-media-embedded-video.vue
  packages/ripple-ui-core/src/index.ts
  packages/ripple-ui-core/src/web-components.ts
Labels: Needs Code review

#358 [R220-330] - Header feedback
  packages/ripple-ui-core/src/components/header/header-actions.css
  packages/ripple-ui-core/src/components/header/header-actions.vue
  packages/ripple-ui-core/src/components/header/header-graphic.css
  packages/ripple-ui-core/src/components/header/header-links.css
  packages/ripple-ui-core/src/components/header/header.css
  packages/ripple-ui-core/src/components/header/header.vue
  packages/ripple-ui-core/src/components/header/hero-header.stories.mdx
  packages/ripple-ui-core/src/components/header/hero-header.vue
  packages/ripple-ui-core/src/components/header/intro-header.stories.mdx
  packages/ripple-ui-core/src/components/header/intro-header.vue
Labels: Needs Code review
