Repository dpc-sdp/ripple-framework, pull requests merged in 2023-03, with the labels that each got.

#461 fix(@dpc-sdp/ripple-ui-core): :bug: fixed typo in media embed
  packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
Labels: uncontroversial

#460 fix(@dpc-sdp/ripple-tide-publication): :bug: fixed pub card not showi…
  packages/ripple-tide-publication/components/TidePublicationChapterCard.vue
Labels: uncontroversial

#462 fix(@dpc-sdp/ripple-tide-event): :bug: fixed crashed when no event li…
  packages/ripple-tide-event/components/TideEventBody.vue
Labels: uncontroversial

#459 [R20-681] Adding custom tables
  docs/components/content/DocsColourTable.vue
  docs/components/content/DocsGradientTable.vue
  docs/components/content/DocsIconSizingTable.vue
  docs/components/content/DocsIconTable.vue
  docs/components/content/DocsLayerStyleTable.vue
  docs/components/content/DocsTypeClassTable.vue
  docs/components/content/DocsTypeTable.vue
  docs/components/content/Swatch.vue
  docs/content/design-system/2.styles/1.colour.md
  docs/content/design-system/2.styles/2.iconography.md
  docs/content/design-system/2.styles/3.typography.md
  docs/content/design-system/2.styles/4.layer-styles.md
  docs/content/design-system/Kitchen sink.md
  docs/nuxt.config.ts
  docs/package.json
  docs/utils/colour.ts
  packages/ripple-ui-core/src/index.ts
  packages/ripple-ui-core/src/styles/components/_table.css
  packages/ripple-ui-core/tokens/settings/color.yaml
  pnpm-lock.yaml
Labels: Needs Code review

#465 fix(@dpc-sdp/ripple-tide-publication): :bug: fixed pub page crashing …
  packages/ripple-tide-publication/utils/processMenu.ts
Labels: uncontroversial

#466 fix(@dpc-sdp/ripple-tide-landing-page): :bug: fixed mapping of key da…
  packages/ripple-tide-landing-page/mapping/components/key-dates/key-dates-mapping.test.ts
  packages/ripple-tide-landing-page/mapping/components/key-dates/key-dates-mapping.ts
  packages/ripple-ui-core/src/components/card/RplCard.css
  packages/ripple-ui-core/src/components/card/RplKeyDatesCard.vue
Labels: uncontroversial

#472 [R20-557] expandable content fix
  packages/ripple-ui-core/src/composables/useAnimateHeight.ts
Labels: Needs Code review, uncontroversial

#475 style: updated theme in storybook
  packages/ripple-storybook/.storybook/themes.js
Labels: uncontroversial

#479 fix(@dpc-sdp/ripple-ui-core): allow a single timeline element
  packages/ripple-ui-core/src/components/timeline/RplTimeline.css
  packages/ripple-ui-core/src/components/timeline/RplTimeline.vue
Labels: Needs Code review

#477 [R20-442] [R20-473] embeded videos
  packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
  packages/ripple-ui-core/src/assets/icons/core/icon-view.svg
  packages/ripple-ui-core/src/assets/icons/custom.js
  packages/ripple-ui-core/src/assets/icons/sprite.js
  packages/ripple-ui-core/src/assets/icons/sprite.svg
  packages/ripple-ui-core/src/components/content/RplContent.css
Labels: Needs Code review

#481 [R20-425] [R20-395] [R20-399] [R20-424] grants QA feedback
  examples/nuxt-app/test/fixtures/landingpage/home.json
  packages/ripple-tide-grant/components/TideGrantTimeline.vue
  packages/ripple-tide-grant/mapping/index.ts
  packages/ripple-tide-grant/types.ts
  packages/ripple-tide-landing-page/mapping/components/timeline/timeline-mapping.test.ts
  packages/ripple-tide-landing-page/mapping/components/timeline/timeline-mapping.ts
  packages/ripple-ui-core/src/components/campaign-banner/RplPrimaryCampaign.vue
  packages/ripple-ui-core/src/components/campaign-banner/RplSecondaryCampaign.vue
  packages/ripple-ui-core/src/components/card-carousel/constants.ts
  packages/ripple-ui-core/src/components/card/RplAvatarCard.vue
  packages/ripple-ui-core/src/components/card/RplCallToActionCard.vue
  packages/ripple-ui-core/src/components/card/RplCategoryGridCard.vue
  packages/ripple-ui-core/src/components/card/RplNavCard.vue
  packages/ripple-ui-core/src/components/card/RplPromoCard.vue
  packages/ripple-ui-core/src/components/content/RplContent.stories.mdx
  packages/ripple-ui-core/src/components/document/RplDocument.vue
  packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
  packages/ripple-ui-core/src/components/timeline/RplTimeline.css
  packages/ripple-ui-core/src/components/timeline/RplTimeline.stories.mdx
  packages/ripple-ui-core/src/components/timeline/RplTimeline.vue
  packages/ripple-ui-core/src/styles/utilities/_focus.css
Labels: Needs Code review

#483 [R20-586] fix modal height for mobile and gallery size for safari
  packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
  packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.vue
  packages/ripple-ui-core/src/components/modal/RplModal.css
  packages/ripple-ui-core/src/components/modal/RplModal.vue
Labels: Needs Code review

#488 [R20-740] make sure link text wraps
  packages/ripple-ui-core/src/components/contact-us/RplContactUs.css
  packages/ripple-ui-core/src/components/text-link/RplTextLink.css
Labels: Needs Code review

#489 [R20-450] callout not applied
  packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
  packages/ripple-tide-event/mapping/index.ts
  packages/ripple-tide-grant/mapping/index.ts
Labels: Needs Code review

#490 fix(@dpc-sdp/nuxt-ripple): fix topics and tags touching
  packages/nuxt-ripple/components/TideBaseLayout.vue
  packages/nuxt-ripple/components/TideTopicTags.vue
Labels: Needs Code review

#487 fix(@dpc-sdp/ripple-tide-api): update doc plugin and testcontent
  packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
  packages/ripple-ui-core/src/components/content/fixtures/testcontent.html
Labels: Needs Code review

#480 [R20-445] adding support for robots.txt
  packages/nuxt-ripple/nuxt.config.ts
  packages/nuxt-ripple/package.json
  packages/nuxt-ripple/robots.config.ts
  pnpm-lock.yaml
Labels: Needs Code review

#499 fix(@dpc-sdp/ripple-ui-core): allow click through on overflowing camp…
  packages/ripple-ui-core/src/components/campaign-banner/RplCampaignBanner.css
Labels: Needs Code review

#500 [R20-454] use percentages for new patterns
  packages/ripple-ui-core/src/assets/patterns/triangles-bottom.svg
  packages/ripple-ui-core/src/assets/patterns/triangles-top.svg
  packages/ripple-ui-core/src/components/header/RplHeaderGraphic.css
Labels: Needs Code review
