Repository dpc-sdp/ripple-framework, pull requests merged in 2023-06, with the labels that each got.

#612 [R20-991][R20-992] template and content updates
  packages/nuxt-ripple-cli/README.md
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/component/index.css.ejs.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/component/index.vue.ejs.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/README.md
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/body-component.vue.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/content-component.vue.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/fixture.json.ts.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/header-component.vue.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/mapping.ts.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/nuxt.config.ts.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/package.json.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/page-component.vue.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/server-middleware.ts.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/server-plugin.ts.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/test.feature.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/types.ts.t
  packages/nuxt-ripple-cli/src/commands/add/helpers.ts
  packages/nuxt-ripple-cli/src/commands/add/index.ts
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/README.md.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/eslint.rc.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/gitignore.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/nuxt.config.ts.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/playground/env.example.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/playground/env.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/playground/nuxt.config.ts.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/README.md.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/app.config.ts.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/env.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/nuxt.config.ts.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
  packages/nuxt-ripple-cli/src/commands/init/index.ts
  packages/nuxt-ripple-cli/src/commands/mock/index.ts
Labels: Needs Code review

#617 [R20-993] conditional logic for arrays
  packages/ripple-tide-landing-page/mapping/components/webforms/webform-conditional-logic.test.ts
  packages/ripple-tide-landing-page/mapping/components/webforms/webform-conditional-logic.ts
  packages/ripple-ui-forms/src/components/RplForm/RplForm.vue
Labels: Needs Code review

#619 [R20-405] design/QA feedback
  packages/ripple-ui-core/src/components/button/RplButton.css
  packages/ripple-ui-core/src/components/expandable/RplExpandable.vue
  packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.vue
  packages/ripple-ui-core/src/components/media-gallery/RplMediaGalleryContent.vue
  packages/ripple-ui-core/src/components/modal/RplModal.css
  packages/ripple-ui-core/src/components/pagination/RplPagination.css
  packages/ripple-ui-core/src/components/pagination/RplPagination.vue
  packages/ripple-ui-core/src/components/slider/RplSlider.vue
  packages/ripple-ui-core/src/composables/useComputedSpeed.ts
Labels: Needs Code review

#620 [R20-891] fix card display, add cta link mapping
  packages/ripple-tide-api/src/utils/mapping-utils.ts
  packages/ripple-tide-landing-page/components/global/TideLandingPage/ContentCollection.vue
  packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.test.ts
  packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.ts
  packages/ripple-tide-landing-page/mapping/components/content-collection/test-data.js
Labels: Needs Code review

#623 [R20-434] Feedback
  packages/ripple-ui-forms/src/components/RplFormActions/RplFormActions.vue
  packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.css
  packages/ripple-ui-forms/src/components/RplFormDropdown/RplFormDropdown.vue
Labels: Needs Code review

#624 fix(@dpc-sdp/ripple-ui-forms): fix RplFormActions variants
  packages/ripple-ui-forms/src/inputs/actions.ts
Labels: Needs Code review

#626 [R20-839] remove native min-max from mapping
  packages/ripple-tide-landing-page/mapping/components/webforms/webforms-mapping.ts
Labels: Needs Code review

#627 [R20-357] add new itemsToLoad mapping
  packages/ripple-tide-landing-page/mapping/components/content-collection/content-collection-mapping.ts
  packages/ripple-tide-landing-page/mapping/components/content-collection/test-data.js
Labels: Needs Code review

#630 [R20-1050] fix linting errors
  package.json
  packages/nuxt-ripple-preview/server/api/tide/oauth.ts
  packages/ripple-ui-core/.stylelintrc.json
  packages/ripple-ui-core/package.json
  packages/ripple-ui-core/src/components/button/RplButton.css
  packages/ripple-ui-core/src/components/data-table/RplDataTable.css
  packages/ripple-ui-core/src/components/search-bar/RplSearchBar.css
  packages/ripple-ui-core/src/components/sitemap/RplSitemap.css
  packages/ripple-ui-core/src/components/tabs/RplTabs.css
  packages/ripple-ui-core/src/styles/components/_table.css
  packages/ripple-ui-core/src/styles/generated/_vars.css
  packages/ripple-ui-core/src/styles/utilities/_focus.css
  packages/ripple-ui-core/src/tokens/settings/layers.yaml
  packages/ripple-ui-core/src/tokens/settings/theme.yaml
  pnpm-lock.yaml
Labels: Needs Code review

#631 [R20-1050] cleaning up browser console warnings
  packages/nuxt-ripple-analytics/plugins/analytics.ts
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/header-component.vue.t
  packages/nuxt-ripple/components/TideBreadcrumbs.vue
  packages/nuxt-ripple/components/TideContentRating.vue
  packages/nuxt-ripple/composables/use-tide-page-meta.ts
  packages/ripple-tide-event/components/TideEventBody.vue
  packages/ripple-tide-event/components/TideEventHeader.vue
  packages/ripple-tide-event/components/TideEventOverview.vue
  packages/ripple-tide-grant/components/TideGrantHeader.vue
  packages/ripple-tide-landing-page/components/global/TideLandingPage/CardCarousel.vue
  packages/ripple-tide-landing-page/components/global/TideLandingPage/HeroHeader.vue
  packages/ripple-tide-landing-page/components/global/TideLandingPage/MediaGallery.vue
  packages/ripple-tide-landing-page/components/global/TideLandingPage/WebForm.vue
  packages/ripple-tide-news/components/TideNewsHeader.vue
  packages/ripple-tide-news/components/global/TideNews.vue
  packages/ripple-tide-publication/components/TidePublicationBody.vue
  packages/ripple-tide-publication/components/TidePublicationHeader.vue
  packages/ripple-ui-core/src/components/description-list/RplDescriptionList.vue
  packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
  packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
  packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.vue
  packages/ripple-ui-core/src/components/modal/RplModal.vue
  packages/ripple-ui-core/src/nuxt/index.ts
  packages/ripple-ui-forms/src/components/RplFormOptions/RplFormOption.vue
  packages/ripple-ui-forms/src/nuxt.ts
Labels: Needs Code review

#628 [R20-1050] content updates
  CONTRIBUTING.md
  examples/nuxt-app/.example.env
  packages/nuxt-ripple-analytics/LICENSE
  packages/nuxt-ripple-analytics/README.md
  packages/nuxt-ripple-cli/LICENSE
  packages/nuxt-ripple-cli/README.md
  packages/nuxt-ripple-preview/README.md
  packages/nuxt-ripple/LICENSE
  packages/nuxt-ripple/README.md
  packages/ripple-storybook/LICENSE
  packages/ripple-storybook/README.md
  packages/ripple-test-utils/LICENSE
  packages/ripple-test-utils/README.md
  packages/ripple-tide-api/LICENSE
  packages/ripple-tide-api/README.md
  packages/ripple-tide-event/LICENSE
  packages/ripple-tide-event/README.md
  packages/ripple-tide-grant/LICENSE
  packages/ripple-tide-grant/README.md
  packages/ripple-tide-landing-page/LICENSE
  packages/ripple-tide-landing-page/README.md
  packages/ripple-tide-media/LICENSE
  packages/ripple-tide-media/README.md
  packages/ripple-tide-news/LICENSE
  packages/ripple-tide-news/README.md
  packages/ripple-tide-publication/LICENSE
  packages/ripple-tide-publication/README.md
  packages/ripple-tide-search/LICENSE
  packages/ripple-tide-search/README.md
  packages/ripple-ui-core/LICENSE
  packages/ripple-ui-core/README.md
  packages/ripple-ui-forms/LICENSE
  packages/ripple-ui-forms/README.md
Labels: Needs Code review

#632 [R20-1050] fix duplicate import warning
  packages/nuxt-ripple-preview/package.json
  packages/nuxt-ripple-preview/pages/oauth/logging-in.vue
  packages/nuxt-ripple-preview/pages/oauth/success.vue
  packages/nuxt-ripple-preview/server/api/tide/oauth.ts
  packages/nuxt-ripple-preview/server/middleware/preview-links.ts
  packages/nuxt-ripple-preview/server/plugins/preview.ts
  packages/nuxt-ripple-preview/server/routes/oauth/login.ts
  packages/nuxt-ripple-preview/utilities/constants.ts
  packages/nuxt-ripple-preview/utilities/index.ts
  packages/nuxt-ripple-preview/utilities/isPreviewPath.ts
  packages/nuxt-ripple-preview/utils/index.ts
Labels: Needs Code review

#629 [R20-1050] cli updates
  packages/nuxt-ripple-cli/README.md
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/component/index.css.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/component/index.vue.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/LICENSE.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/nuxt.config.ts.t
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/package.json.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/LICENSE.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/README.md.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/eslint.rc.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/jest.config.js.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/nuxt.config.ts.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/package.json.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/README.md.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/env.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/nuxt.config.ts.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/package.json.t
Labels: Needs Code review

#621 [DOCS MIGRATION CONTENT BRANCH]
  docs/content/design-system/4.styles/colour.md
  docs/content/design-system/5.components/accordion.md
  docs/content/design-system/5.components/acknowledgment.md
  docs/content/design-system/5.components/alert.md
  docs/content/design-system/5.components/block-quote.md
  docs/content/design-system/5.components/breadcrumb.md
  docs/content/design-system/5.components/button.md
  docs/content/design-system/5.components/call-to-action.md
  docs/content/design-system/5.components/callout.md
  docs/content/design-system/5.components/campaign-banner.md
  docs/content/design-system/5.components/card.md
  docs/content/design-system/5.components/carousel.md
  docs/content/design-system/5.components/category-grid.md
  docs/content/design-system/5.components/checkbox.md
  docs/content/design-system/5.components/chip.md
  docs/content/design-system/5.components/date-input.md
  docs/content/design-system/5.components/dropdown.md
  docs/content/design-system/5.components/form-alert.md
  docs/content/design-system/5.components/form.md
  docs/content/design-system/5.components/input-field.md
  docs/content/design-system/5.components/primary-navigation.md
Labels: DO NOT MERGE, WIP

#641 [R20-1066] update date text
  packages/ripple-ui-forms/src/components/RplFormDate/RplFormDate.vue
Labels: Needs Code review

#644 chore: remove block level elements breaking highlight in hero
  packages/nuxt-ripple-cli/src/commands/add/_templates/add/content-type/header-component.vue.t
  packages/ripple-tide-event/components/TideEventHeader.vue
  packages/ripple-tide-grant/components/TideGrantHeader.vue
  packages/ripple-tide-landing-page/components/global/TideLandingPage/HeroHeader.vue
  packages/ripple-tide-news/components/TideNewsHeader.vue
  packages/ripple-tide-publication/components/TidePublicationHeader.vue
  packages/ripple-ui-core/src/components/header/RplHeroHeader.vue
Labels: Needs Code review

#640 [R20-1050] add fonts to 'external' assets
  packages/ripple-ui-core/src/nuxt/index.ts
Labels: Needs Code review

#638 [R20-771] add support for intro buttons (to matc…
  packages/ripple-tide-landing-page/components/global/TideLandingPage/IntroBanner.vue
  packages/ripple-tide-landing-page/mapping/components/intro-banner/intro-banner-mapping.test.ts
  packages/ripple-tide-landing-page/mapping/components/intro-banner/intro-banner-mapping.ts
  packages/ripple-ui-core/src/components/header/RplHeader.css
  packages/ripple-ui-core/src/components/header/RplHeaderLinks.css
  packages/ripple-ui-core/src/components/header/RplHeaderLinks.vue
  packages/ripple-ui-core/src/components/header/RplIntroHeader.stories.mdx
  packages/ripple-ui-core/src/components/header/RplIntroHeader.vue
  packages/ripple-ui-core/src/components/header/constants.ts
Labels: Needs Code review

#643 [R20-1067] Add selectors to help locate elements
  packages/nuxt-ripple/components/TideUpdatedDate.vue
  packages/ripple-ui-core/src/components/layout/RplLayout.vue
Labels: uncontroversial

#639 chore: minor cleanup of package.json files
  examples/nuxt-app/package.json
  packages/nuxt-ripple-analytics/package.json
  packages/nuxt-ripple-cli/package.json
  packages/nuxt-ripple-preview/package.json
  packages/nuxt-ripple/package.json
  packages/ripple-storybook/package.json
  packages/ripple-test-utils/package.json
  packages/ripple-tide-api/package.json
  packages/ripple-tide-event/package.json
  packages/ripple-tide-grant/package.json
  packages/ripple-tide-landing-page/package.json
  packages/ripple-tide-media/package.json
  packages/ripple-tide-news/package.json
  packages/ripple-tide-publication/package.json
  packages/ripple-tide-search/package.json
  packages/ripple-ui-core/package.json
  packages/ripple-ui-forms/package.json
  pnpm-lock.yaml
Labels: Needs Code review

#654 [R20-969] update price range
  packages/nuxt-ripple/utils/anchorLinks.test.ts
  packages/nuxt-ripple/utils/anchorLinks.ts
  packages/nuxt-ripple/utils/createHandler.ts
  packages/nuxt-ripple/utils/formatPriceRange.test.ts
  packages/nuxt-ripple/utils/formatPriceRange.ts
  packages/ripple-tide-api/src/utils/breadcrumbs.test.ts
  packages/ripple-tide-api/src/utils/breadcrumbs.ts
  packages/ripple-tide-api/src/utils/formatPriceRange.test.ts
  packages/ripple-tide-api/src/utils/formatPriceRange.ts
  packages/ripple-tide-api/src/utils/groupDynamicComponents.test.ts
  packages/ripple-tide-api/src/utils/groupDynamicComponents.ts
Labels: Needs Code review

#657 [R20-1050] move search related runtime config options
  .circleci/config.yml
  examples/nuxt-app/nuxt.config.ts
  packages/nuxt-ripple-cli/src/commands/init/_templates/layer/latest/playground/nuxt.config.ts.t
  packages/nuxt-ripple-cli/src/commands/init/_templates/site/latest/nuxt.config.ts.t
  packages/ripple-tide-landing-page/nuxt.config.ts
  packages/ripple-tide-search/nuxt.config.ts
Labels: Needs Code review

#655 [R20-1050] remove file extensions to fix reference dev mode
  packages/nuxt-ripple-preview/utils/index.ts
Labels: Needs Code review

#662 docs: add basic guide for creating layers
  CHANGELOG.md
  docs/components/content/DocsExample.vue
  docs/components/content/DocsThemeChooser.vue
  docs/content/design-system/5.components/checkbox.md
  docs/content/design-system/5.components/filter-lockup.md
  docs/content/framework/3.guides/5.creating-new-layers.md
  docs/package.json
  docs/public/assets/fonts/VIC-RegularItalic.woff2
  lerna.json
  packages/nuxt-ripple-analytics/CHANGELOG.md
  packages/nuxt-ripple-analytics/package.json
  packages/nuxt-ripple-preview/CHANGELOG.md
  packages/nuxt-ripple-preview/package.json
  packages/nuxt-ripple-preview/utils/index.ts
  packages/nuxt-ripple/CHANGELOG.md
  packages/nuxt-ripple/package.json
  packages/ripple-tide-event/CHANGELOG.md
  packages/ripple-tide-event/package.json
  packages/ripple-tide-grant/CHANGELOG.md
  packages/ripple-tide-grant/package.json
  packages/ripple-tide-landing-page/CHANGELOG.md
  packages/ripple-tide-landing-page/package.json
  packages/ripple-tide-media/CHANGELOG.md
  packages/ripple-tide-media/package.json
  packages/ripple-tide-news/CHANGELOG.md
  packages/ripple-tide-news/package.json
  packages/ripple-tide-publication/CHANGELOG.md
  packages/ripple-tide-publication/package.json
  packages/ripple-tide-search/CHANGELOG.md
  packages/ripple-tide-search/package.json
  packages/ripple-ui-core/CHANGELOG.md
  packages/ripple-ui-core/package.json
  packages/ripple-ui-core/src/components/image/RplImg.vue
  packages/ripple-ui-core/src/components/vertical-nav/RplVerticalNav.vue
  packages/ripple-ui-forms/CHANGELOG.md
  packages/ripple-ui-forms/package.json
  packages/ripple-ui-forms/src/components/RplFormOptions/RplFormCheckboxGroup.stories.mdx
  packages/ripple-ui-forms/src/components/StorybookInputFixture/StorybookInputFixture.vue
  pnpm-lock.yaml
Labels: Needs Code review

#672 docs: add content types guide
  docs/content/framework/3.guides/4.creating-content-types.md
Labels: Needs Code review

#674 [R20-538] adding component tests
  packages/ripple-ui-core/src/components/alert/RplAlert.cy.ts
  packages/ripple-ui-core/src/components/data-table/RplDataTable.cy.ts
  packages/ripple-ui-core/src/components/data-table/RplDataTable.stories.mdx
  packages/ripple-ui-core/src/components/data-table/fixtures/sample.ts
  packages/ripple-ui-core/src/components/footer/RplFooter.cy.ts
  packages/ripple-ui-core/src/components/footer/RplFooter.stories.mdx
  packages/ripple-ui-core/src/components/footer/fixtures/sample.ts
  packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.cy.ts
  packages/ripple-ui-core/src/components/media-gallery/RplMediaGallery.cy.ts
  packages/ripple-ui-core/src/components/pagination/RplPagination.cy.ts
  packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.cy.ts
  packages/ripple-ui-core/src/components/tabs/RplTabs.cy.ts
  packages/ripple-ui-core/src/components/vertical-nav/RplVerticalNav.cy.ts
  packages/ripple-ui-core/src/components/vertical-nav/RplVerticalNav.stories.mdx
  packages/ripple-ui-core/src/components/vertical-nav/fixtures/sample.ts
Labels: Needs Code review
