Repository dpc-sdp/ripple-framework, pull requests merged in 2023-01, with the labels that each got.

#359 fix(@dpc-sdp/ripple-ui-core): remove tabindex, update button
  packages/ripple-ui-core/src/components/button/button.vue
  packages/ripple-ui-core/src/components/card/call-to-action.vue
Labels: Needs Code review, uncontroversial

#361 fix(@dpc-sdp/ripple-ui-core): page links disappeared from storybook
  packages/ripple-ui-core/src/components/page-links/page-links.vue
Labels: uncontroversial

#360 [R20-279][R20-281][R20-282][R20-283][R20-284] card feedback
  examples/nuxt-app/test/fixtures/landingpage/home.json
  packages/ripple-tide-landing-page/src/components/CallToAction.vue
  packages/ripple-tide-landing-page/src/components/NavCard.vue
  packages/ripple-tide-landing-page/src/components/PromoCard.vue
  packages/ripple-tide-landing-page/src/mapping/page-components/call-to-action/call-to-action-mapping.ts
  packages/ripple-ui-core/src/components/card/avatar-card.stories.mdx
  packages/ripple-ui-core/src/components/card/avatar-card.vue
  packages/ripple-ui-core/src/components/card/call-to-action.stories.mdx
  packages/ripple-ui-core/src/components/card/call-to-action.vue
  packages/ripple-ui-core/src/components/card/card.css
  packages/ripple-ui-core/src/components/card/category-grid-card.stories.mdx
  packages/ripple-ui-core/src/components/card/category-grid-card.vue
  packages/ripple-ui-core/src/components/card/constants.ts
  packages/ripple-ui-core/src/components/card/nav-card.stories.mdx
  packages/ripple-ui-core/src/components/card/nav-card.vue
  packages/ripple-ui-core/src/components/card/promo-card.stories.mdx
  packages/ripple-ui-core/src/components/card/promo-card.vue
  packages/ripple-ui-core/src/components/image/constants.ts
  packages/ripple-ui-core/src/components/image/image.vue
Labels: Needs Code review

#383 [R20-398,R20-427] Bug fixes
  packages/nuxt-ripple/components/TideSidebarContactUs.vue
  packages/ripple-ui-core/src/components/campaign-banner/secondary-campaign.vue
Labels: uncontroversial
