Repository dpc-sdp/ripple-framework, pull requests merged in 2023-04, with the labels that each got.

#521 [R20-811] make sure expanded content is visible
  packages/ripple-ui-core/src/components/expandable/RplExpandable.vue
Labels: Needs Code review

#520 [R20-799] fix accessible links in carousels and search results
  packages/ripple-ui-core/src/components/slider/RplSlider.vue
  packages/ripple-ui-core/src/composables/useAccessibleContainer.ts
Labels: Needs Code review

#523 [R20-765] search qa items
  packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.css
  packages/ripple-ui-core/src/components/primary-nav/components/search-form/RplPrimaryNavSearchForm.vue
  packages/ripple-ui-core/src/components/search-bar/RplSearchBar.css
  packages/ripple-ui-core/src/components/search-bar/RplSearchBar.vue
Labels: Needs Code review

#526 [R20-709] Add favicon
  packages/nuxt-ripple/components/TideBaseLayout.vue
  packages/nuxt-ripple/public/android-chrome-192x192.png
  packages/nuxt-ripple/public/android-chrome-512x512.png
  packages/nuxt-ripple/public/apple-touch-icon.png
  packages/nuxt-ripple/public/browserconfig.xml
  packages/nuxt-ripple/public/favicon-16x16.png
  packages/nuxt-ripple/public/favicon-32x32.png
  packages/nuxt-ripple/public/favicon.ico
  packages/nuxt-ripple/public/mstile-150x150.png
  packages/nuxt-ripple/public/safari-pinned-tab.svg
  packages/nuxt-ripple/public/site.webmanifest
Labels: uncontroversial

#533 [R20-846] use highlight for promo cards
  packages/ripple-tide-api/src/utils/mapping-utils.ts
  packages/ripple-tide-landing-page/components/global/TideLandingPage/PromoCard.vue
Labels: Needs Code review

#530 [R20-348] primary nav design feedback
  packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenu.css
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenu.vue
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuAction.vue
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuList.vue
  packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
  packages/ripple-ui-core/src/components/primary-nav/constants.ts
Labels: Needs Code review

#537 [R20-855] add tab support for primary nav
  packages/ripple-ui-core/src/components/primary-nav/RplPrimaryNav.vue
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenu.vue
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuAction.vue
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuHomeButton.vue
  packages/ripple-ui-core/src/components/primary-nav/components/mega-menu/RplPrimaryNavMegaMenuList.vue
  packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBar.vue
  packages/ripple-ui-core/src/components/primary-nav/components/nav-bar/RplPrimaryNavBarAction.vue
  packages/ripple-ui-core/src/components/primary-nav/components/quick-exit/RplPrimaryNavQuickExit.vue
  packages/ripple-ui-core/src/components/primary-nav/constants.ts
  packages/ripple-ui-core/src/components/primary-nav/fixtures/sample.ts
  packages/ripple-ui-core/src/composables/usePrimaryNavFocus.ts
Labels: Needs Code review

#538 [R20-760] print style feedback and additions
  packages/ripple-tide-api/src/utils/markup-transpiler/default-plugins.ts
  packages/ripple-ui-core/src/components/button/RplButton.css
  packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.css
  packages/ripple-ui-core/src/components/media-embed/RplMediaEmbed.vue
  packages/ripple-ui-core/src/components/result-listing/RplSearchResult.css
  packages/ripple-ui-core/src/components/result-listing/RplSearchResult.vue
  packages/ripple-ui-forms/src/components/RplFormActions/RplFormActions.vue
Labels: Needs Code review

#542 [R20-407] share previews
  packages/nuxt-ripple/components/TideAlerts.vue
  packages/nuxt-ripple/components/TideBaseLayout.vue
  packages/nuxt-ripple/mapping/base/index.ts
  packages/ripple-tide-api/src/services/tide-page.ts
Labels: Needs Code review

#550 [R20-281] navigation and cta card feedback
  packages/ripple-ui-core/src/components/card/RplCallToActionCard.vue
  packages/ripple-ui-core/src/components/card/RplCard.css
Labels: Needs Code review, uncontroversial
